# pull official base image
FROM python:3.11-slim-bookworm

# set working directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat-openbsd gcc postgresql \
  && apt-get -y install libpq-dev \
  && apt-get clean

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

# create static/media dirs
RUN mkdir -p /usr/src/app/staticfiles /usr/src/app/mediafiles

# # entrypoint (waits for db etc.)
# ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# ✅ THIS WAS MISSING (MOST IMPORTANT)
CMD ["python", "telegram_bot/poller.py"]
