# Generated by Django 5.0.2 on 2026-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="transaction_hash",
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_id",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
